### ISSUE TITLE
CPU->CR0 |= (1<<31)

### ISSUE THREAD

**Issue by AntiVegan** [lukemills/mmu#1]
Please see latest commit for a list of cases that fail/do not behave as expected.

**Comment by lukemills** [comment]
Hate to say it, but this isn't actually an error with the map/vtp code, it's an issue with the offsets.

The last three hex digits of the virtual address should be zeroed out before adding in the physical offset using get4kphysoffset(phys).

I have tested the code as such an it works when said action is done.
